### PR TITLE
add more fields, available in 2024.44.32

### PR DESCRIPTION
**Pull request by patrickdemers6**
# Description

Adding more fields.

-   LocatedAtHome
-   LocatedAtWork
-   LocatedAtFavorite
-   SettingDistanceUnit
-   SettingTemperatureUnit
-   Setting24HourTime
-   SettingTirePressureUnit
-   SettingChargeUnit
-   ClimateSeatCoolingFrontLeft
-   ClimateSeatCoolingFrontRight

## Type of change

Please select all options that apply to this change:

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update

# Checklist:

Confirm you have completed the following steps:

- [ ] My code follows the style of this project.
- [ ] I have performed a self-review of my code.
- [ ] I have made corresponding updates to the documentation.
- [ ] I have added/updated unit tests to cover my changes.
- [ ] I have added/updated integration tests to cover my changes.

### CODE REVIEW

**Review by aaronpkahn — APPROVED** [review]

**Comment by jbanyer** [comment]
Nice!

Do the `Located*` fields require `vehicle_location` scope?

Do they cause the "location tracking" icon to be displayed constantly in the vehicle, as the `Location` field does?

**Comment by patrickdemers6** [comment]
Hey @jbanyer 
These fields provide information about the vehicle's location through booleans. They do not reveal the vehicle's actual location, so they do not require location scope and do not show the icon.

**Comment by rawmean** [comment]
Thanks for adding these. 
Is there a better way for devs to become aware of these changes (other than monitoring pull requests)? 
When these fields are added, devs must wait for their car to get the associated car firmware before being able to test it. This can take a while. Can devs somehow register their VINs to get the associated update sooner to test these changes?

Are you planning to populate display_name? It is currently populated as (even in the recent holiday update):
`{'key': 'VehicleName', 'value': {'invalid': True}`

**Comment by stx** [comment]
@patrickdemers6 Looks like this has been merged for awhile. Can you tag a release with this?

**Comment by patrickdemers6** [comment]
Published v0.4.1 @stx 

Happy New Years 🎉

**Comment by stx** [comment]
@patrickdemers6 You too. Thank you!

**Pull request merged**
