### PR TITLE
Fix setup steps typo

### LINKED ISSUE #134: README example command lines for openssl do not match
In the "Setup Steps" section, step 2 creates a file called "private-key.pem", but in step 5, the command references "private_key.pem". Copy/pasting these commands yields an error because of the mismatched file name.

### PR DESCRIPTION
**Pull request by sjhill01**
# Description

Updated the README file so example openssl commands align on use of private key file name.

Fixes #134 

## Type of change

Please select all options that apply to this change:

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation update

# Checklist:

Confirm you have completed the following steps:

- [x] My code follows the style of this project.
- [x] I have performed a self-review of my code.
- [x] I have made corresponding updates to the documentation.
- [N/A] I have added/updated unit tests to cover my changes.
- [ N/A I have added/updated integration tests to cover my changes.

### CODE REVIEW

**Comment by patrickdemers6** [comment]
Thanks for catching this. Could you revise commit and PR name to be a bit more descriptive? Something like "fix setup steps typo".

**Comment by sjhill01** [comment]
Done - didn't notice the default that got pulled in from my commit there!

**Comment by patrickdemers6** [comment]
Could you amend commit as well? Nice to have PR title and commit title matching!

**Comment by sjhill01** [comment]
Done.

**Review by patrickdemers6 — APPROVED** [review]

**Comment by patrickdemers6** [comment]
Thanks for your contribution! :partying_face:

**Pull request merged**
